Build stuff
Signed-off-by: karlatec <karlatec@protonmail.com>

diff --git a/.github/workflows/gerrit-change-printer.yml b/.github/workflows/gerrit-change-printer.yml
--- a/.github/workflows/gerrit-change-printer.yml
+++ b/.github/workflows/gerrit-change-printer.yml
@@ -13,29 +13,84 @@ jobs:
     steps:
       - name: Print client_payload
         run: |
-          echo '${{ toJson(inputs.client_payload) }}'
+          echo '${{ toJson(inputs.client_payload) }}' | jq
 
-  report:
+  tests:
     runs-on: ubuntu-latest
     needs:
       - print-patchset
     steps:
-      - name: Report results
+      - name: Checkout SPDK
+        uses: actions/checkout@v4
+        with:
+          repository: spdk/spdk
+          submodules: recursive
+      - name: Fetch change from Gerrit
         run: |
-          # Credits to https://github.com/spdk-community-ci/dispatcher/blob/main/.github/workflows/autorun.yml
-          set -e
+          git fetch https://review.spdk.io/gerrit/spdk/spdk ${{ toJson(inputs.client_payload).patchSet.ref }} && git checkout FETCH_HEAD
+      - name: Fetch submodules
+        run: |
+          git submodule update --init --recursive
+      - name: Install dependencies
+        # This of course needs to be moved into a separate job which will tarball the build
+        # and move it to jobs running the tests.
+        run: |
+          sudo ./scripts/pkgdep.sh --uring --developer-tools
+          sudo apt-get install meson python3-pyelftools
+      - name: Prepare autotest configuration file
+        run: |
+          cat <<- EOF >> autotest.config
+            SPDK_RUN_VALGRIND=0
+            SPDK_TEST_UNITTEST=1
+            SPDK_TEST_BLOCKDEV=1
+            SPDK_TEST_ISAL=1
+            SPDK_TEST_REDUCE=1
+            SPDK_TEST_VBDEV_COMPRESS=1
+            SPDK_TEST_CRYPTO=1
+            SPDK_TEST_FTL=1
+            SPDK_TEST_OCF=0
+            SPDK_TEST_RAID=1
+            SPDK_TEST_RBD=1
+            SPDK_TEST_URING=1
+            SPDK_TEST_NVME_CUSE=1
+            SPDK_TEST_BLOBFS=1
+            SPDK_TEST_VFIOUSER=1
+            SPDK_TEST_DAOS=0
+            SPDK_RUN_ASAN=1
+            SPDK_RUN_UBSAN=1
+            SPDK_TEST_XNVME=1
+          EOF
+      - name: Build SPDK and run unit tests
+        run: |
+          ls -la
+          pwd
+          echo $GITHUB_WORKSPACE
+          rootdir=$GITHUB_WORKSPACE
+          source ./test/common/autobuild_common.sh ./autotest.config
+          unittest_build
+          ./test/unit/unittest.sh
 
-          VOTE=-1
-          if [[ "${{ needs.print-patchset.result }}" == "success" ]]; then
-            VOTE=1
-          fi
+  # report:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - print-patchset
+  #   steps:
+  #     - name: Report results
+  #       run: |
+  #         # Credits to https://github.com/spdk-community-ci/dispatcher/blob/main/.github/workflows/autorun.yml
+  #         set -e
 
-          # For demonstration purposes, as not to set any actual vote and only comment.
-          VOTE=0
+  #         VOTE=-1
+  #         if [[ "${{ needs.print-patchset.result }}" == "success" ]]; then
+  #           VOTE=1
+  #         fi
 
-          # Commented out for now, so I don't accidentally spam the Gerrit server.
-          # curl -X POST https://review.spdk.io/gerrit/a/changes/${{ fromJson(inputs.client_payload).change.number }}/revisions/${{ fromJson(inputs.client_payload).patchSet.number }}/review \
-          # --user "${{ secrets.GERRIT_BOT_USER }}:${{ secrets.GERRIT_BOT_HTTP_PASSWD }}" \
-          # --header "Content-Type: application/json" \
-          # --data "{'message': '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID', 'labels': {'Verified': $VOTE}}" \
-          # --fail-with-body
+  #         # For demonstration purposes, as not to set any actual vote and only comment.
+  #         VOTE=0
+
+  #         # Commented out for now, so I don't accidentally spam the Gerrit server.
+  #         # curl -X POST https://review.spdk.io/gerrit/a/changes/${{ fromJson(inputs.client_payload).change.number }}/revisions/${{ fromJson(inputs.client_payload).patchSet.number }}/review \
+  #         # --user "${{ secrets.GERRIT_BOT_USER }}:${{ secrets.GERRIT_BOT_HTTP_PASSWD }}" \
+  #         # --header "Content-Type: application/json" \
+  #         # --data "{'message': '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID', 'labels': {'Verified': $VOTE}}" \
+  #         # --fail-with-body
